#! /bin/sh

export XDG_CURRENT_DESKTOP='bspwm'

# startup
pidof -q picom || { picom & }
feh --bg-scale ~/backgrounds/leaves.png &
~/.config/polybar/launch.sh
setxkbmap us
xmodmap ~/.config/bspwm/scripts/.Xmodmap

# fix cursor
xsetroot -cursor_name left_ptr &

pkill -x sxhkd; sxhkd -c ~/.config/bspwm/sxhkdrc &

for monitor in $(xrandr -q | grep -w 'connected' | cut -d' ' -f1); do
    bspc monitor "$monitor" -d '1' '2' '3' '4' '5' '6'
done

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
